sudo: required

services:
  - docker

before_install:
  - docker pull tailordev/pandas
  - docker ps -a
  - docker run carlad/sinatra pip install pytest
  - pip install pytest

script:
  - python -m pytest tests
