language: python
sudo: false
matrix:
  include:
    - python: 2.7
      addons:
        apt:
          packages:
            - python-scipy
            - python-pandas
            
    - python: 3.5
    - python: 3.4
    - python: 2.7
addons:
  apt:
    packages:
    - python-scipy
    - python-pandas

script:
  - python -m pytest tests
